version: "3.9"

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: stray_pets_api
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - stray-pets-postgres:/var/lib/postgresql/data
  # redis:
  #   image: redis:7.0
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - youvisa-redis:/var/lib/redis/data


volumes:
  stray-pets-postgres:
  #stray-pets-redis: